name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: sandpit-binh-nguyen-2bj6
  SERVICE: bg-app-server
  REGION: europe-west2

jobs:
  deploy-cloud-function:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Authenticate
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          project_id: ${{ env.PROJECT_ID }}
          env_vars: "BNG_SLACK_SIGNING_SECRET=${{ secrets.BNG_SLACK_SIGNING_SECRET }},BNG_SLACK_BOT_TOKEN=${{ secrets.BNG_SLACK_BOT_TOKEN }},BNG_DALL_E_SCRAPER_BASE_URL=${{ secrets.BNG_DALL_E_SCRAPER_BASE_URL }}"
          source: ./

      - name: Show output URL
        run: echo ${{ steps.deploy.outputs.url }}
